'use strict';
(async()=>{
const $=id=>document.getElementById(id), canvas=$('game'), ctx={createImageData:(width,height)=>({width,height})};let renderer;try{renderer=new PolygonScene(canvas);}catch(e){$('loading').textContent=e.message;return;}
const held=new Map(), keys=new Set();let engine,ready=false,audio=null,audioStarted=false,musicOn=true,effectsOn=true,musicNode=null,musicGain=null,musicTrack=-1,musicBuffers=[],nextFX=0,fxTimer=0,last=0,accumulator=0,lastState=-1,lastBest=0,lastGas=false,selectedPad=null,padPresent=false,audioPromise=null,renderMs=0,slowFrames=0,renderEvery=1,frameNo=0;
let image=ctx.createImageData(480,300);const BEST='fuerther-kaerwa-polygon-best-v1';
function resizeGame(){if(!ready)return;const stage=$('stage'),desired=Math.max(320,Math.min(1200,Math.round(stage.clientWidth/stage.clientHeight*300)));if(image.width===desired)return;const width=engine._web_resize(desired);image=ctx.createImageData(width,300);}
window.addEventListener('resize',resizeGame);window.visualViewport?.addEventListener('resize',resizeGame);
let noticeTimer;function report(s){$('status').textContent=s;if(/konnte|nicht verfügbar|Hier bitte/.test(s)){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{$('notice').hidden=true;},6000);}}
function command(n){if(ready)engine._web_command(n);}
function clearInput(){held.clear();keys.clear();document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));lastGas=false;}
function gamepads(){try{return navigator.getGamepads?.()||[];}catch{return [];}}
function input(){let left=keys.has('ArrowLeft'),right=keys.has('ArrowRight'),gas=keys.has('Space')||keys.has('ArrowUp'),brake=keys.has('ArrowDown');for(const v of held.values()){left ||=v==='left';right ||=v==='right';gas ||=v==='gas';brake ||=v==='brake';}
 const pads=gamepads(),available=Array.from(pads).filter(Boolean);let pad=available.find(p=>p.index===selectedPad)||available[0];padPresent=!!pad;if(pad){selectedPad=pad.index;const x=pad.axes[0]||0,y=pad.axes[1]||0;left ||=x<-.3;right ||=x>.3;gas ||=!!pad.buttons[0]?.pressed;brake ||=y>.5||!!pad.buttons[1]?.pressed;}
 return {steer:Number(right)-Number(left),gas:Number(gas),brake:Number(brake)};
}
function stopMusic(){if(musicNode){try{musicNode.stop();}catch{}musicNode.disconnect();musicNode=null;}musicTrack=-1;}
function selectMusic(state){if(!audio||!audioStarted)return;const track=state===0?0:state===4?1:2;if(track===musicTrack)return;stopMusic();if(!musicBuffers[track])return;musicNode=audio.createBufferSource();musicNode.buffer=musicBuffers[track];musicNode.loop=track!==1;musicGain.gain.value=musicOn?(track===2?.906:.844):0;musicNode.connect(musicGain);musicNode.start();musicTrack=track;}
function pumpFX(){if(!audioStarted||audio.state!=='running'||!ready)return;if(nextFX<audio.currentTime)nextFX=audio.currentTime+.015;const control=input();let blocks=0;while(nextFX<audio.currentTime+.10&&blocks++<5){const n=1024,ptr=engine._web_audio(n,control.gas,control.steer),pcm=new Int16Array(engine.HEAPU8.buffer,ptr,n*2),buffer=audio.createBuffer(2,n,22050);for(let c=0;c<2;c++){const dest=buffer.getChannelData(c);for(let i=0;i<n;i++)dest[i]=pcm[i*2+c]/32768;}const source=audio.createBufferSource();source.buffer=buffer;source.connect(audio.destination);source.start(nextFX);nextFX+=n/22050;}}
function wakeAudio(){if(!audio)return;try{const resume=audio.resume();resume?.catch(()=>{});const pulse=audio.createBufferSource();pulse.buffer=audio.createBuffer(1,1,audio.sampleRate);pulse.connect(audio.destination);pulse.start(0);}catch{}}
async function unlockAudio(){wakeAudio();if(audioStarted){if(!document.hidden&&!engine._web_paused()&&audio.state!=='running')await audio.resume();return;}if(audioPromise)return audioPromise;audioPromise=(async()=>{try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('Audio nicht unterstützt');try{if(navigator.audioSession)navigator.audioSession.type='playback';}catch{}audio=new AC();wakeAudio();musicGain=audio.createGain();musicGain.connect(audio.destination);await audio.resume();report('Musik wird geladen …');musicBuffers=await Promise.all(['intro','countdown','rennen'].map(async n=>{const r=await fetch('audio/'+n+'.mp3?v='+encodeURIComponent(window.kaerwaVersion||'polygon-1'));if(!r.ok)throw Error('Audiodatei fehlt');return audio.decodeAudioData(await r.arrayBuffer());}));audioStarted=true;selectMusic(engine._web_state());nextFX=audio.currentTime+.02;fxTimer=setInterval(pumpFX,25);$('listen').hidden=true;void syncAudio();report('Bereit · Touch, Tastatur oder Joystick');}catch(e){console.error(e);report('Ton konnte nicht starten. Das Rennen ist ohne Ton spielbar.');}finally{audioPromise=null;}})();return audioPromise;}
async function syncAudio(){if(!audioStarted)return;const shouldPause=document.hidden||engine._web_paused();if(shouldPause){if(audio.state==='running')await audio.suspend();return;}if(audio.state!=='running')await audio.resume();musicGain.gain.value=musicOn?(musicTrack===2?.906:.844):0; }
function start(){if(!ready)return;void unlockAudio();if(matchMedia('(pointer:coarse)').matches&&!document.fullscreenElement&&$('app').requestFullscreen){$('app').requestFullscreen().then(()=>{try{screen.orientation.lock('landscape').catch(()=>{});}catch{}}).catch(()=>{});}void unlockAudio();command(1);$('welcome').hidden=true;}
let updateAvailable=false,checkingUpdate=false;
async function checkUpdate(){if(checkingUpdate||document.hidden)return;checkingUpdate=true;try{const r=await fetch('version.json?check='+Date.now(),{cache:'no-store'});if(r.ok){const m=await r.json();if(m.version&&m.version!==window.kaerwaVersion)updateAvailable=true;}}catch{}finally{checkingUpdate=false;}}
$('update').onclick=()=>{const url=new URL(location.href);url.searchParams.set('update',Date.now());location.replace(url.href);};
setInterval(()=>void checkUpdate(),60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void checkUpdate();});
function refreshUI(state){$('update').hidden=!updateAvailable||state===1||state===4;$('welcome').hidden=state!==0;$('restart').hidden=state!==2&&state!==3;const running=state===1||state===4;$('pause').disabled=!running;$('pause').classList.toggle('resume',!!engine._web_paused());$('pause').setAttribute('aria-label',engine._web_paused()?'Weiterfahren':'Pause');$('pause').title=engine._web_paused()?'Weiterfahren':'Pause';if(state!==lastState){selectMusic(state);if(state===2){const best=engine._web_best();if(best!==lastBest){try{localStorage.setItem(BEST,String(best));}catch{}lastBest=best;}report('Ziel erreicht · Bestzeit '+best.toFixed(2)+' s');}else if(state===3)report('Zeit abgelaufen · Noch ein Rennen?');else if(state===4)report('Gleich geht’s los!');else if(state===1)report(padPresent?'Joystick verbunden':'Lenken und Gas gleichzeitig halten');lastState=state;}}
function loop(now){if(!ready)return;resizeGame();const dt=last?Math.min((now-last)/1000,.10):0;last=now;const c=input(),state=engine._web_state();if(c.gas&&!lastGas&&(state===0||state===2||state===3))start();lastGas=!!c.gas;accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps++<6){engine._web_step(1/60,c.steer,c.gas,c.brake,Number(padPresent));accumulator-=1/60;}if(++frameNo%renderEvery===0&&!document.hidden){const t=performance.now();renderer.draw({now,state:engine._web_state(),paused:!!engine._web_paused(),position:engine._web_position(),speed:engine._web_speed(),lane:engine._web_lane(),remaining:engine._web_remaining(),contacts:engine._web_contacts(),best:engine._web_best(),elapsed:engine._web_elapsed(),finish:engine._web_finish_distance(),countdown:engine._web_countdown(),steer:c.steer,brake:c.brake,traffic:n=>engine._web_traffic_position(n),wagon:k=>engine._web_wagon(k)});renderMs=performance.now()-t;if(renderMs>21)slowFrames++;else slowFrames=Math.max(0,slowFrames-1);if(slowFrames>15)renderEvery=2;}refreshUI(engine._web_state());requestAnimationFrame(loop);}
for(const button of document.querySelectorAll('[data-control]')){button.addEventListener('pointerdown',e=>{if(!ready)return;e.preventDefault();button.setPointerCapture(e.pointerId);held.set(e.pointerId,button.dataset.control);button.classList.add('held');void unlockAudio();});const release=e=>{held.delete(e.pointerId);if(!Array.from(held.values()).includes(button.dataset.control))button.classList.remove('held');};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);button.addEventListener('contextmenu',e=>e.preventDefault());}
$('help').addEventListener('toggle',()=>{if($('help').open){clearInput();command(6);void syncAudio();}});
$('start').onclick=start;$('listen').onclick=()=>void unlockAudio();$('restart').onclick=()=>{command(3);clearInput();void unlockAudio();};$('pause').onclick=()=>{command(2);clearInput();if(!engine._web_paused())void unlockAudio();void syncAudio();};$('music').onclick=()=>{void unlockAudio();musicOn=!musicOn;command(4);$('music').classList.toggle('muted',!musicOn);$('music').setAttribute('aria-label',musicOn?'Musik ausschalten':'Musik einschalten');$('music').setAttribute('aria-pressed',musicOn);void syncAudio();};$('sound').onclick=()=>{void unlockAudio();effectsOn=!effectsOn;command(5);$('sound').classList.toggle('muted',!effectsOn);$('sound').setAttribute('aria-label',effectsOn?'Fahrgeräusche ausschalten':'Fahrgeräusche einschalten');$('sound').setAttribute('aria-pressed',effectsOn);};
$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('app').requestFullscreen){await $('app').requestFullscreen();try{await screen.orientation.lock('landscape');}catch{}}else report('Hier bitte das Handy quer halten; Vollbild ist im Browser nicht verfügbar.');}catch{report('Vollbild nicht verfügbar · Querformat funktioniert trotzdem.');}};
window.addEventListener('keydown',e=>{if(!ready)return;const recognized=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyP','KeyR','KeyM','KeyS','KeyJ'].includes(e.code);if(!recognized)return;e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyP')$('pause').click();if(e.code==='KeyR'){$('restart').onclick();}if(e.code==='KeyM')$('music').click();if(e.code==='KeyS')$('sound').click();if(e.code==='KeyJ'){const pads=Array.from(gamepads()).filter(Boolean);const i=pads.findIndex(p=>p.index===selectedPad);selectedPad=pads[(i+1)%pads.length]?.index??null;}if(e.code==='Space'||e.code==='ArrowUp')void unlockAudio();});window.addEventListener('keyup',e=>keys.delete(e.code));
function leave(){clearInput();command(6);last=0;accumulator=0;if(audioStarted)void audio.suspend();}canvas.addEventListener('webglcontextlost',leave);window.addEventListener('blur',leave);document.addEventListener('visibilitychange',()=>{if(document.hidden)leave();else{last=0;accumulator=0;if(audioStarted&&!engine._web_paused())void syncAudio();}});window.addEventListener('pagehide',leave);
try{if(location.protocol==='file:')throw Error('Bitte über GitHub Pages öffnen. Ein Doppelklick auf index.html lädt WebAssembly nicht zuverlässig.');engine=await KaerwaEngine({locateFile:p=>p+'?v='+encodeURIComponent(window.kaerwaVersion||'polygon-1')});let saved=0;try{saved=Number(localStorage.getItem(BEST))||0;}catch{}engine._web_init(saved);lastBest=engine._web_best();ready=true;resizeGame();$('loading').hidden=true;$('welcome').hidden=false;for(const id of ['start','listen','music','sound'])$(id).disabled=false;report('Bereit · Für Musik einmal tippen');requestAnimationFrame(loop);
// Read-only diagnostics for reproducible browser tests.
window.kaerwaDiagnostics=()=>({state:engine._web_state(),paused:!!engine._web_paused(),position:engine._web_position(),speed:engine._web_speed(),lane:engine._web_lane(),remaining:engine._web_remaining(),contacts:engine._web_contacts(),best:engine._web_best(),audio:audio?.state||'off',held:Array.from(held.values()),width:image.width,height:image.height,scene:renderer.diagnostics(),renderMs,renderEvery});
}catch(e){console.error(e);$('loading').textContent=e.message+' Bitte die Seite nach vollständigem Upload neu laden.';report('Spiel konnte nicht geladen werden.');}
})();
